name: Dependabot Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Run weekly on Sunday at midnight UTC

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: charmbracelet/meta/.github/actions/dependabot-sync@main
        with:
          repo_name: ${{ github.event.repository.name }}
